const os = require('os');
// console.log(os.arch());
// console.log(os.cpus());
// console.log('Ram free GB: '+ (os.freemem()/1024/1024/1024));
// console.log(os.totalmem());
// console.log(os.hostname());
// console.log(os.platform());
// console.log(os.tmpdir());
// console.log(os.type());
// console.log(os.userInfo());
